#ifndef C_SOURCE_KIT_D_SHIM_H
#define C_SOURCE_KIT_D_SHIM_H

// Generated by Tools/generate-sourcekitd-shim.swift. Do not edit by hand.

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct {
    uint64_t data[3];
} SwiftSourceKitDVariant;

typedef bool (*SwiftSourceKitDVariantDictionaryApplier)(
    void *key,
    SwiftSourceKitDVariant *value,
    void *context
);

void swift_sourcekitd_response_get_value(
    void *function,
    void * resp,
    SwiftSourceKitDVariant *out
);
size_t swift_sourcekitd_variant_array_get_count(
    void *function,
    SwiftSourceKitDVariant * array
);
void swift_sourcekitd_variant_array_get_value(
    void *function,
    SwiftSourceKitDVariant * array,
    size_t index,
    SwiftSourceKitDVariant *out
);
bool swift_sourcekitd_variant_bool_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
);
const void * swift_sourcekitd_variant_data_get_ptr(
    void *function,
    SwiftSourceKitDVariant * obj
);
size_t swift_sourcekitd_variant_data_get_size(
    void *function,
    SwiftSourceKitDVariant * obj
);
bool swift_sourcekitd_variant_dictionary_apply(
    void *function,
    SwiftSourceKitDVariant *dictionary,
    SwiftSourceKitDVariantDictionaryApplier applier,
    void *context
);
double swift_sourcekitd_variant_double_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
);
int32_t swift_sourcekitd_variant_get_type(
    void *function,
    SwiftSourceKitDVariant * obj
);
int64_t swift_sourcekitd_variant_int64_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
);
const char * swift_sourcekitd_variant_string_get_ptr(
    void *function,
    SwiftSourceKitDVariant * obj
);
void * swift_sourcekitd_variant_uid_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
);
#endif
