// Generated by Tools/generate-sourcekit-uid-constants.swift. Do not edit by hand.
// Source of truth: Tests/Fixtures/sourcekit/UIDs.py.

public extension SourceKitUID {
    // Root aliases cover keys and requests with unambiguous Swift names.
    static let versionMajor = Key.versionMajor
    static let versionMinor = Key.versionMinor
    static let versionPatch = Key.versionPatch
    static let results = Key.results
    static let request = Key.request
    static let notification = Key.notification
    static let kind = Key.kind
    static let accessLevel = Key.accessLevel
    static let setterAccessLevel = Key.setterAccessLevel
    static let keyword = Key.keyword
    static let name = Key.name
    static let usr = Key.usr
    static let originalUSR = Key.originalUSR
    static let defaultImplementationOf = Key.defaultImplementationOf
    static let interestedUSR = Key.interestedUSR
    static let genericParams = Key.genericParams
    static let genericRequirements = Key.genericRequirements
    static let docFullAsXML = Key.docFullAsXML
    static let docComment = Key.docComment
    static let line = Key.line
    static let column = Key.column
    static let receiverUSR = Key.receiverUSR
    static let receivers = Key.receivers
    static let isDynamic = Key.isDynamic
    static let isImplicit = Key.isImplicit
    static let filePath = Key.filePath
    static let moduleInterfaceName = Key.moduleInterfaceName
    static let hash = Key.hash
    static let severity = Key.severity
    static let offset = Key.offset
    static let length = Key.length
    static let sourceFile = Key.sourceFile
    static let primaryFile = Key.primaryFile
    static let enableSyntaxMap = Key.enableSyntaxMap
    static let enableStructure = Key.enableStructure
    static let id = Key.id
    static let description = Key.description
    static let typeName = Key.typeName
    static let runtimeName = Key.runtimeName
    static let selectorName = Key.selectorName
    static let annotatedDecl = Key.annotatedDecl
    static let fullyAnnotatedDecl = Key.fullyAnnotatedDecl
    static let fullyAnnotatedGenericSignature = Key.fullyAnnotatedGenericSignature
    static let signatures = Key.signatures
    static let activeSignature = Key.activeSignature
    static let parameters = Key.parameters
    static let activeParameter = Key.activeParameter
    static let docBrief = Key.docBrief
    static let context = Key.context
    static let typeRelation = Key.typeRelation
    static let moduleImportDepth = Key.moduleImportDepth
    static let numBytesToErase = Key.numBytesToErase
    static let notRecommended = Key.notRecommended
    static let declarations = Key.declarations
    static let enableDeclarations = Key.enableDeclarations
    static let annotations = Key.annotations
    static let diagnosticStage = Key.diagnosticStage
    static let syntaxMap = Key.syntaxMap
    static let isSystem = Key.isSystem
    static let related = Key.related
    static let inherits = Key.inherits
    static let conforms = Key.conforms
    static let extends = Key.extends
    static let dependencies = Key.dependencies
    static let entities = Key.entities
    static let nameOffset = Key.nameOffset
    static let nameLength = Key.nameLength
    static let bodyOffset = Key.bodyOffset
    static let bodyLength = Key.bodyLength
    static let docOffset = Key.docOffset
    static let docLength = Key.docLength
    static let isActive = Key.isActive
    static let isLocal = Key.isLocal
    static let inheritedTypes = Key.inheritedTypes
    static let attributes = Key.attributes
    static let attribute = Key.attribute
    static let elements = Key.elements
    static let subStructure = Key.subStructure
    static let ranges = Key.ranges
    static let fixits = Key.fixits
    static let generatedBuffers = Key.generatedBuffers
    static let bufferText = Key.bufferText
    static let originalLocation = Key.originalLocation
    static let educationalNotePaths = Key.educationalNotePaths
    static let formatOptions = Key.formatOptions
    static let codeCompleteOptions = Key.codeCompleteOptions
    static let typeContextInfoOptions = Key.typeContextInfoOptions
    static let conformingMethodListOptions = Key.conformingMethodListOptions
    static let filterRules = Key.filterRules
    static let nextRequestStart = Key.nextRequestStart
    static let popular = Key.popular
    static let unpopular = Key.unpopular
    static let hide = Key.hide
    static let platform = Key.platform
    static let isDeprecated = Key.isDeprecated
    static let isUnavailable = Key.isUnavailable
    static let isOptional = Key.isOptional
    static let isAsync = Key.isAsync
    static let message = Key.message
    static let introduced = Key.introduced
    static let deprecated = Key.deprecated
    static let obsoleted = Key.obsoleted
    static let cancelBuilds = Key.cancelBuilds
    static let removeCache = Key.removeCache
    static let typeUsr = Key.typeUsr
    static let containerTypeUsr = Key.containerTypeUsr
    static let baseName = Key.baseName
    static let argNames = Key.argNames
    static let selectorPieces = Key.selectorPieces
    static let nameKind = Key.nameKind
    static let localizationKey = Key.localizationKey
    static let isZeroArgSelector = Key.isZeroArgSelector
    static let swiftVersion = Key.swiftVersion
    static let value = Key.value
    static let enableDiagnostics = Key.enableDiagnostics
    static let groupName = Key.groupName
    static let actionName = Key.actionName
    static let synthesizedExtension = Key.synthesizedExtension
    static let usingSwiftArgs = Key.usingSwiftArgs
    static let names = Key.names
    static let uids = Key.uids
    static let syntacticOnly = Key.syntacticOnly
    static let parentLoc = Key.parentLoc
    static let isTestCandidate = Key.isTestCandidate
    static let overrides = Key.overrides
    static let associatedUSRs = Key.associatedUSRs
    static let moduleName = Key.moduleName
    static let relatedDecls = Key.relatedDecls
    static let simplified = Key.simplified
    static let rangeContent = Key.rangeContent
    static let cancelOnSubsequentRequest = Key.cancelOnSubsequentRequest
    static let includeNonEditableBaseNames = Key.includeNonEditableBaseNames
    static let renameLocations = Key.renameLocations
    static let locations = Key.locations
    static let nameType = Key.nameType
    static let newName = Key.newName
    static let categorizedEdits = Key.categorizedEdits
    static let categorizedRanges = Key.categorizedRanges
    static let rangesWorthNote = Key.rangesWorthNote
    static let edits = Key.edits
    static let endLine = Key.endLine
    static let endColumn = Key.endColumn
    static let argIndex = Key.argIndex
    static let text = Key.text
    static let category = Key.category
    static let categories = Key.categories
    static let isFunctionLike = Key.isFunctionLike
    static let isNonProtocolType = Key.isNonProtocolType
    static let refactorActions = Key.refactorActions
    static let retrieveRefactorActions = Key.retrieveRefactorActions
    static let symbolGraph = Key.symbolGraph
    static let retrieveSymbolGraph = Key.retrieveSymbolGraph
    static let parentContexts = Key.parentContexts
    static let referencedSymbols = Key.referencedSymbols
    static let isSPI = Key.isSPI
    static let actionUID = Key.actionUID
    static let actionUnavailableReason = Key.actionUnavailableReason
    static let compileID = Key.compileID
    static let compilerArgsString = Key.compilerArgsString
    static let implicitMembers = Key.implicitMembers
    static let expectedTypes = Key.expectedTypes
    static let members = Key.members
    static let typeBuffer = Key.typeBuffer
    static let expressionTypeList = Key.expressionTypeList
    static let expressionOffset = Key.expressionOffset
    static let expressionLength = Key.expressionLength
    static let expressionType = Key.expressionType
    static let variableTypeList = Key.variableTypeList
    static let variableOffset = Key.variableOffset
    static let variableLength = Key.variableLength
    static let variableType = Key.variableType
    static let variableTypeExplicit = Key.variableTypeExplicit
    static let fullyQualified = Key.fullyQualified
    static let canonicalizeType = Key.canonicalizeType
    static let internalDiagnostic = Key.internalDiagnostic
    static let vfsName = Key.vfsName
    static let vfsOptions = Key.vfsOptions
    static let files = Key.files
    static let optimizeForIDE = Key.optimizeForIDE
    static let requiredBystanders = Key.requiredBystanders
    static let reusingASTContext = Key.reusingASTContext
    static let completionMaxASTContextReuseCount = Key.completionMaxASTContextReuseCount
    static let completionCheckDependencyInterval = Key.completionCheckDependencyInterval
    static let annotatedTypename = Key.annotatedTypename
    static let compileOperation = Key.compileOperation
    static let effectiveAccess = Key.effectiveAccess
    static let declarationLang = Key.declarationLang
    static let secondarySymbols = Key.secondarySymbols
    static let simulateLongRequest = Key.simulateLongRequest
    static let isSynthesized = Key.isSynthesized
    static let bufferName = Key.bufferName
    static let barriersEnabled = Key.barriersEnabled
    static let expansions = Key.expansions
    static let macroRoles = Key.macroRoles
    static let expandedMacroReplacements = Key.expandedMacroReplacements
    static let indexStorePath = Key.indexStorePath
    static let indexUnitOutputPath = Key.indexUnitOutputPath
    static let includeLocals = Key.includeLocals
    static let compress = Key.compress
    static let ignoreClangModules = Key.ignoreClangModules
    static let includeSystemModules = Key.includeSystemModules
    static let ignoreStdlib = Key.ignoreStdlib
    static let disableImplicitModules = Key.disableImplicitModules
    static let compilerArgs = Key.compilerArgs
    static let sourceText = Key.sourceText
    static let protocolVersion = Request.protocolVersion
    static let compilerVersion = Request.compilerVersion
    static let crashWithExit = Request.crashWithExit
    static let demangle = Request.demangle
    static let mangleSimpleClass = Request.mangleSimpleClass
    static let index = Request.index
    static let docInfo = Request.docInfo
    static let codeComplete = Request.codeComplete
    static let codeCompleteOpen = Request.codeCompleteOpen
    static let codeCompleteClose = Request.codeCompleteClose
    static let codeCompleteUpdate = Request.codeCompleteUpdate
    static let codeCompleteCacheOnDisk = Request.codeCompleteCacheOnDisk
    static let codeCompleteSetPopularAPI = Request.codeCompleteSetPopularAPI
    static let codeCompleteSetCustom = Request.codeCompleteSetCustom
    static let signatureHelp = Request.signatureHelp
    static let typeContextInfo = Request.typeContextInfo
    static let conformingMethodList = Request.conformingMethodList
    static let activeRegions = Request.activeRegions
    static let cursorInfo = Request.cursorInfo
    static let rangeInfo = Request.rangeInfo
    static let relatedIdents = Request.relatedIdents
    static let editorOpen = Request.editorOpen
    static let editorOpenInterface = Request.editorOpenInterface
    static let editorOpenHeaderInterface = Request.editorOpenHeaderInterface
    static let editorOpenSwiftSourceInterface = Request.editorOpenSwiftSourceInterface
    static let editorOpenSwiftTypeInterface = Request.editorOpenSwiftTypeInterface
    static let editorExtractTextFromComment = Request.editorExtractTextFromComment
    static let editorClose = Request.editorClose
    static let editorReplaceText = Request.editorReplaceText
    static let editorFormatText = Request.editorFormatText
    static let editorExpandPlaceholder = Request.editorExpandPlaceholder
    static let editorFindUSR = Request.editorFindUSR
    static let editorFindInterfaceDoc = Request.editorFindInterfaceDoc
    static let buildSettingsRegister = Request.buildSettingsRegister
    static let nameTranslation = Request.nameTranslation
    static let markupToXML = Request.markupToXML
    static let statistics = Request.statistics
    static let findRenameRanges = Request.findRenameRanges
    static let findLocalRenameRanges = Request.findLocalRenameRanges
    static let semanticRefactoring = Request.semanticRefactoring
    static let enableCompileNotifications = Request.enableCompileNotifications
    static let testNotification = Request.testNotification
    static let collectExpressionType = Request.collectExpressionType
    static let collectVariableType = Request.collectVariableType
    static let globalConfiguration = Request.globalConfiguration
    static let dependencyUpdated = Request.dependencyUpdated
    static let compile = Request.compile
    static let compileClose = Request.compileClose
    static let enableRequestBarriers = Request.enableRequestBarriers
    static let syntacticMacroExpansion = Request.syntacticMacroExpansion
    static let indexToStore = Request.indexToStore
    static let polyglotAST = Request.polyglotAST
    static let compilerArguments = Key.compilerArgs
    static let declarationFile = Key.filePath
    static let declarationOffset = Key.offset

    enum Key {
        public static let versionMajor: SourceKitUID = "key.version_major"
        public static let versionMinor: SourceKitUID = "key.version_minor"
        public static let versionPatch: SourceKitUID = "key.version_patch"
        public static let results: SourceKitUID = "key.results"
        public static let request: SourceKitUID = "key.request"
        public static let notification: SourceKitUID = "key.notification"
        public static let kind: SourceKitUID = "key.kind"
        public static let accessLevel: SourceKitUID = "key.accessibility"
        public static let setterAccessLevel: SourceKitUID = "key.setter_accessibility"
        public static let keyword: SourceKitUID = "key.keyword"
        public static let name: SourceKitUID = "key.name"
        public static let usr: SourceKitUID = "key.usr"
        public static let originalUSR: SourceKitUID = "key.original_usr"
        public static let defaultImplementationOf: SourceKitUID = "key.default_implementation_of"
        public static let interestedUSR: SourceKitUID = "key.interested_usr"
        public static let genericParams: SourceKitUID = "key.generic_params"
        public static let genericRequirements: SourceKitUID = "key.generic_requirements"
        public static let docFullAsXML: SourceKitUID = "key.doc.full_as_xml"
        public static let docComment: SourceKitUID = "key.doc_comment"
        public static let line: SourceKitUID = "key.line"
        public static let column: SourceKitUID = "key.column"
        public static let receiverUSR: SourceKitUID = "key.receiver_usr"
        public static let receivers: SourceKitUID = "key.receivers"
        public static let isDynamic: SourceKitUID = "key.is_dynamic"
        public static let isImplicit: SourceKitUID = "key.is_implicit"
        public static let filePath: SourceKitUID = "key.filepath"
        public static let moduleInterfaceName: SourceKitUID = "key.module_interface_name"
        public static let hash: SourceKitUID = "key.hash"
        public static let severity: SourceKitUID = "key.severity"
        public static let offset: SourceKitUID = "key.offset"
        public static let length: SourceKitUID = "key.length"
        public static let sourceFile: SourceKitUID = "key.sourcefile"
        public static let primaryFile: SourceKitUID = "key.primary_file"
        public static let enableSyntaxMap: SourceKitUID = "key.enablesyntaxmap"
        public static let enableStructure: SourceKitUID = "key.enablesubstructure"
        public static let id: SourceKitUID = "key.id"
        public static let description: SourceKitUID = "key.description"
        public static let typeName: SourceKitUID = "key.typename"
        public static let runtimeName: SourceKitUID = "key.runtime_name"
        public static let selectorName: SourceKitUID = "key.selector_name"
        public static let annotatedDecl: SourceKitUID = "key.annotated_decl"
        public static let fullyAnnotatedDecl: SourceKitUID = "key.fully_annotated_decl"
        public static let fullyAnnotatedGenericSignature: SourceKitUID = "key.fully_annotated_generic_signature"
        public static let signatures: SourceKitUID = "key.signatures"
        public static let activeSignature: SourceKitUID = "key.active_signature"
        public static let parameters: SourceKitUID = "key.parameters"
        public static let activeParameter: SourceKitUID = "key.active_parameter"
        public static let docBrief: SourceKitUID = "key.doc.brief"
        public static let context: SourceKitUID = "key.context"
        public static let typeRelation: SourceKitUID = "key.typerelation"
        public static let moduleImportDepth: SourceKitUID = "key.moduleimportdepth"
        public static let numBytesToErase: SourceKitUID = "key.num_bytes_to_erase"
        public static let notRecommended: SourceKitUID = "key.not_recommended"
        public static let declarations: SourceKitUID = "key.declarations"
        public static let enableDeclarations: SourceKitUID = "key.enabledeclarations"
        public static let annotations: SourceKitUID = "key.annotations"
        public static let semanticTokens: SourceKitUID = "key.semantic_tokens"
        public static let diagnosticStage: SourceKitUID = "key.diagnostic_stage"
        public static let syntaxMap: SourceKitUID = "key.syntaxmap"
        public static let isSystem: SourceKitUID = "key.is_system"
        public static let related: SourceKitUID = "key.related"
        public static let inherits: SourceKitUID = "key.inherits"
        public static let conforms: SourceKitUID = "key.conforms"
        public static let extends: SourceKitUID = "key.extends"
        public static let dependencies: SourceKitUID = "key.dependencies"
        public static let entities: SourceKitUID = "key.entities"
        public static let nameOffset: SourceKitUID = "key.nameoffset"
        public static let nameLength: SourceKitUID = "key.namelength"
        public static let bodyOffset: SourceKitUID = "key.bodyoffset"
        public static let bodyLength: SourceKitUID = "key.bodylength"
        public static let docOffset: SourceKitUID = "key.docoffset"
        public static let docLength: SourceKitUID = "key.doclength"
        public static let isActive: SourceKitUID = "key.is_active"
        public static let isLocal: SourceKitUID = "key.is_local"
        public static let inheritedTypes: SourceKitUID = "key.inheritedtypes"
        public static let attributes: SourceKitUID = "key.attributes"
        public static let attribute: SourceKitUID = "key.attribute"
        public static let elements: SourceKitUID = "key.elements"
        public static let subStructure: SourceKitUID = "key.substructure"
        public static let ranges: SourceKitUID = "key.ranges"
        public static let fixits: SourceKitUID = "key.fixits"
        public static let generatedBuffers: SourceKitUID = "key.generated_buffers"
        public static let bufferText: SourceKitUID = "key.buffer_text"
        public static let originalLocation: SourceKitUID = "key.original_location"
        public static let diagnostics: SourceKitUID = "key.diagnostics"
        public static let educationalNotePaths: SourceKitUID = "key.educational_note_paths"
        public static let formatOptions: SourceKitUID = "key.editor.format.options"
        public static let codeCompleteOptions: SourceKitUID = "key.codecomplete.options"
        public static let typeContextInfoOptions: SourceKitUID = "key.typecontextinfo.options"
        public static let conformingMethodListOptions: SourceKitUID = "key.conformingmethods.options"
        public static let filterRules: SourceKitUID = "key.codecomplete.filterrules"
        public static let nextRequestStart: SourceKitUID = "key.nextrequeststart"
        public static let popular: SourceKitUID = "key.popular"
        public static let unpopular: SourceKitUID = "key.unpopular"
        public static let hide: SourceKitUID = "key.hide"
        public static let platform: SourceKitUID = "key.platform"
        public static let isDeprecated: SourceKitUID = "key.is_deprecated"
        public static let isUnavailable: SourceKitUID = "key.is_unavailable"
        public static let isOptional: SourceKitUID = "key.is_optional"
        public static let isAsync: SourceKitUID = "key.is_async"
        public static let message: SourceKitUID = "key.message"
        public static let introduced: SourceKitUID = "key.introduced"
        public static let deprecated: SourceKitUID = "key.deprecated"
        public static let obsoleted: SourceKitUID = "key.obsoleted"
        public static let cancelBuilds: SourceKitUID = "key.cancel_builds"
        public static let removeCache: SourceKitUID = "key.removecache"
        public static let typeUsr: SourceKitUID = "key.typeusr"
        public static let containerTypeUsr: SourceKitUID = "key.containertypeusr"
        public static let moduleGroups: SourceKitUID = "key.modulegroups"
        public static let baseName: SourceKitUID = "key.basename"
        public static let argNames: SourceKitUID = "key.argnames"
        public static let selectorPieces: SourceKitUID = "key.selectorpieces"
        public static let nameKind: SourceKitUID = "key.namekind"
        public static let localizationKey: SourceKitUID = "key.localization_key"
        public static let isZeroArgSelector: SourceKitUID = "key.is_zero_arg_selector"
        public static let swiftVersion: SourceKitUID = "key.swift_version"
        public static let value: SourceKitUID = "key.value"
        public static let enableDiagnostics: SourceKitUID = "key.enablediagnostics"
        public static let groupName: SourceKitUID = "key.groupname"
        public static let actionName: SourceKitUID = "key.actionname"
        public static let synthesizedExtension: SourceKitUID = "key.synthesizedextensions"
        public static let usingSwiftArgs: SourceKitUID = "key.usingswiftargs"
        public static let names: SourceKitUID = "key.names"
        public static let uids: SourceKitUID = "key.uids"
        public static let syntacticOnly: SourceKitUID = "key.syntactic_only"
        public static let parentLoc: SourceKitUID = "key.parent_loc"
        public static let isTestCandidate: SourceKitUID = "key.is_test_candidate"
        public static let overrides: SourceKitUID = "key.overrides"
        public static let associatedUSRs: SourceKitUID = "key.associated_usrs"
        public static let moduleName: SourceKitUID = "key.modulename"
        public static let relatedDecls: SourceKitUID = "key.related_decls"
        public static let simplified: SourceKitUID = "key.simplified"
        public static let rangeContent: SourceKitUID = "key.rangecontent"
        public static let cancelOnSubsequentRequest: SourceKitUID = "key.cancel_on_subsequent_request"
        public static let includeNonEditableBaseNames: SourceKitUID = "key.include_non_editable_base_names"
        public static let renameLocations: SourceKitUID = "key.renamelocations"
        public static let locations: SourceKitUID = "key.locations"
        public static let nameType: SourceKitUID = "key.nametype"
        public static let newName: SourceKitUID = "key.newname"
        public static let categorizedEdits: SourceKitUID = "key.categorizededits"
        public static let categorizedRanges: SourceKitUID = "key.categorizedranges"
        public static let rangesWorthNote: SourceKitUID = "key.rangesworthnote"
        public static let edits: SourceKitUID = "key.edits"
        public static let endLine: SourceKitUID = "key.endline"
        public static let endColumn: SourceKitUID = "key.endcolumn"
        public static let argIndex: SourceKitUID = "key.argindex"
        public static let text: SourceKitUID = "key.text"
        public static let category: SourceKitUID = "key.category"
        public static let categories: SourceKitUID = "key.categories"
        public static let isFunctionLike: SourceKitUID = "key.is_function_like"
        public static let isNonProtocolType: SourceKitUID = "key.is_non_protocol_type"
        public static let refactorActions: SourceKitUID = "key.refactor_actions"
        public static let retrieveRefactorActions: SourceKitUID = "key.retrieve_refactor_actions"
        public static let symbolGraph: SourceKitUID = "key.symbol_graph"
        public static let retrieveSymbolGraph: SourceKitUID = "key.retrieve_symbol_graph"
        public static let parentContexts: SourceKitUID = "key.parent_contexts"
        public static let referencedSymbols: SourceKitUID = "key.referenced_symbols"
        public static let isSPI: SourceKitUID = "key.is_spi"
        public static let actionUID: SourceKitUID = "key.actionuid"
        public static let actionUnavailableReason: SourceKitUID = "key.actionunavailablereason"
        public static let compileID: SourceKitUID = "key.compileid"
        public static let compilerArgsString: SourceKitUID = "key.compilerargs-string"
        public static let implicitMembers: SourceKitUID = "key.implicitmembers"
        public static let expectedTypes: SourceKitUID = "key.expectedtypes"
        public static let members: SourceKitUID = "key.members"
        public static let typeBuffer: SourceKitUID = "key.printedtypebuffer"
        public static let expressionTypeList: SourceKitUID = "key.expression_type_list"
        public static let expressionOffset: SourceKitUID = "key.expression_offset"
        public static let expressionLength: SourceKitUID = "key.expression_length"
        public static let expressionType: SourceKitUID = "key.expression_type"
        public static let variableTypeList: SourceKitUID = "key.variable_type_list"
        public static let variableOffset: SourceKitUID = "key.variable_offset"
        public static let variableLength: SourceKitUID = "key.variable_length"
        public static let variableType: SourceKitUID = "key.variable_type"
        public static let variableTypeExplicit: SourceKitUID = "key.variable_type_explicit"
        public static let fullyQualified: SourceKitUID = "key.fully_qualified"
        public static let canonicalizeType: SourceKitUID = "key.canonicalize_type"
        public static let internalDiagnostic: SourceKitUID = "key.internal_diagnostic"
        public static let vfsName: SourceKitUID = "key.vfs.name"
        public static let vfsOptions: SourceKitUID = "key.vfs.options"
        public static let files: SourceKitUID = "key.files"
        public static let optimizeForIDE: SourceKitUID = "key.optimize_for_ide"
        public static let requiredBystanders: SourceKitUID = "key.required_bystanders"
        public static let reusingASTContext: SourceKitUID = "key.reusingastcontext"
        public static let completionMaxASTContextReuseCount: SourceKitUID = "key.completion_max_astcontext_reuse_count"
        public static let completionCheckDependencyInterval: SourceKitUID = "key.completion_check_dependency_interval"
        public static let annotatedTypename: SourceKitUID = "key.annotated.typename"
        public static let compileOperation: SourceKitUID = "key.compile_operation"
        public static let effectiveAccess: SourceKitUID = "key.effective_access"
        public static let declarationLang: SourceKitUID = "key.decl_lang"
        public static let secondarySymbols: SourceKitUID = "key.secondary_symbols"
        public static let simulateLongRequest: SourceKitUID = "key.simulate_long_request"
        public static let isSynthesized: SourceKitUID = "key.is_synthesized"
        public static let bufferName: SourceKitUID = "key.buffer_name"
        public static let barriersEnabled: SourceKitUID = "key.barriers_enabled"
        public static let expansions: SourceKitUID = "key.expansions"
        public static let macroRoles: SourceKitUID = "key.macro_roles"
        public static let expandedMacroReplacements: SourceKitUID = "key.expanded_macro_replacements"
        public static let indexStorePath: SourceKitUID = "key.index_store_path"
        public static let indexUnitOutputPath: SourceKitUID = "key.index_unit_output_path"
        public static let includeLocals: SourceKitUID = "key.include_locals"
        public static let compress: SourceKitUID = "key.compress"
        public static let ignoreClangModules: SourceKitUID = "key.ignore_clang_modules"
        public static let includeSystemModules: SourceKitUID = "key.include_system_modules"
        public static let ignoreStdlib: SourceKitUID = "key.ignore_stdlib"
        public static let disableImplicitModules: SourceKitUID = "key.disable_implicit_modules"
        public static let compilerArgs: SourceKitUID = "key.compilerargs"
        public static let sourceText: SourceKitUID = "key.sourcetext"

        public static let all: [SourceKitUID] = [
            versionMajor,
            versionMinor,
            versionPatch,
            results,
            request,
            notification,
            kind,
            accessLevel,
            setterAccessLevel,
            keyword,
            name,
            usr,
            originalUSR,
            defaultImplementationOf,
            interestedUSR,
            genericParams,
            genericRequirements,
            docFullAsXML,
            docComment,
            line,
            column,
            receiverUSR,
            receivers,
            isDynamic,
            isImplicit,
            filePath,
            moduleInterfaceName,
            hash,
            severity,
            offset,
            length,
            sourceFile,
            primaryFile,
            enableSyntaxMap,
            enableStructure,
            id,
            description,
            typeName,
            runtimeName,
            selectorName,
            annotatedDecl,
            fullyAnnotatedDecl,
            fullyAnnotatedGenericSignature,
            signatures,
            activeSignature,
            parameters,
            activeParameter,
            docBrief,
            context,
            typeRelation,
            moduleImportDepth,
            numBytesToErase,
            notRecommended,
            declarations,
            enableDeclarations,
            annotations,
            semanticTokens,
            diagnosticStage,
            syntaxMap,
            isSystem,
            related,
            inherits,
            conforms,
            extends,
            dependencies,
            entities,
            nameOffset,
            nameLength,
            bodyOffset,
            bodyLength,
            docOffset,
            docLength,
            isActive,
            isLocal,
            inheritedTypes,
            attributes,
            attribute,
            elements,
            subStructure,
            ranges,
            fixits,
            generatedBuffers,
            bufferText,
            originalLocation,
            diagnostics,
            educationalNotePaths,
            formatOptions,
            codeCompleteOptions,
            typeContextInfoOptions,
            conformingMethodListOptions,
            filterRules,
            nextRequestStart,
            popular,
            unpopular,
            hide,
            platform,
            isDeprecated,
            isUnavailable,
            isOptional,
            isAsync,
            message,
            introduced,
            deprecated,
            obsoleted,
            cancelBuilds,
            removeCache,
            typeUsr,
            containerTypeUsr,
            moduleGroups,
            baseName,
            argNames,
            selectorPieces,
            nameKind,
            localizationKey,
            isZeroArgSelector,
            swiftVersion,
            value,
            enableDiagnostics,
            groupName,
            actionName,
            synthesizedExtension,
            usingSwiftArgs,
            names,
            uids,
            syntacticOnly,
            parentLoc,
            isTestCandidate,
            overrides,
            associatedUSRs,
            moduleName,
            relatedDecls,
            simplified,
            rangeContent,
            cancelOnSubsequentRequest,
            includeNonEditableBaseNames,
            renameLocations,
            locations,
            nameType,
            newName,
            categorizedEdits,
            categorizedRanges,
            rangesWorthNote,
            edits,
            endLine,
            endColumn,
            argIndex,
            text,
            category,
            categories,
            isFunctionLike,
            isNonProtocolType,
            refactorActions,
            retrieveRefactorActions,
            symbolGraph,
            retrieveSymbolGraph,
            parentContexts,
            referencedSymbols,
            isSPI,
            actionUID,
            actionUnavailableReason,
            compileID,
            compilerArgsString,
            implicitMembers,
            expectedTypes,
            members,
            typeBuffer,
            expressionTypeList,
            expressionOffset,
            expressionLength,
            expressionType,
            variableTypeList,
            variableOffset,
            variableLength,
            variableType,
            variableTypeExplicit,
            fullyQualified,
            canonicalizeType,
            internalDiagnostic,
            vfsName,
            vfsOptions,
            files,
            optimizeForIDE,
            requiredBystanders,
            reusingASTContext,
            completionMaxASTContextReuseCount,
            completionCheckDependencyInterval,
            annotatedTypename,
            compileOperation,
            effectiveAccess,
            declarationLang,
            secondarySymbols,
            simulateLongRequest,
            isSynthesized,
            bufferName,
            barriersEnabled,
            expansions,
            macroRoles,
            expandedMacroReplacements,
            indexStorePath,
            indexUnitOutputPath,
            includeLocals,
            compress,
            ignoreClangModules,
            includeSystemModules,
            ignoreStdlib,
            disableImplicitModules,
            compilerArgs,
            sourceText,
        ]
    }

    enum Request {
        public static let protocolVersion: SourceKitUID = "source.request.protocol_version"
        public static let compilerVersion: SourceKitUID = "source.request.compiler_version"
        public static let crashWithExit: SourceKitUID = "source.request.crash_exit"
        public static let demangle: SourceKitUID = "source.request.demangle"
        public static let mangleSimpleClass: SourceKitUID = "source.request.mangle_simple_class"
        public static let index: SourceKitUID = "source.request.indexsource"
        public static let docInfo: SourceKitUID = "source.request.docinfo"
        public static let codeComplete: SourceKitUID = "source.request.codecomplete"
        public static let codeCompleteOpen: SourceKitUID = "source.request.codecomplete.open"
        public static let codeCompleteClose: SourceKitUID = "source.request.codecomplete.close"
        public static let codeCompleteUpdate: SourceKitUID = "source.request.codecomplete.update"
        public static let codeCompleteCacheOnDisk: SourceKitUID = "source.request.codecomplete.cache.ondisk"
        public static let codeCompleteSetPopularAPI: SourceKitUID = "source.request.codecomplete.setpopularapi"
        public static let codeCompleteSetCustom: SourceKitUID = "source.request.codecomplete.setcustom"
        public static let signatureHelp: SourceKitUID = "source.request.signaturehelp"
        public static let typeContextInfo: SourceKitUID = "source.request.typecontextinfo"
        public static let conformingMethodList: SourceKitUID = "source.request.conformingmethods"
        public static let activeRegions: SourceKitUID = "source.request.activeregions"
        public static let cursorInfo: SourceKitUID = "source.request.cursorinfo"
        public static let rangeInfo: SourceKitUID = "source.request.rangeinfo"
        public static let relatedIdents: SourceKitUID = "source.request.relatedidents"
        public static let editorOpen: SourceKitUID = "source.request.editor.open"
        public static let editorOpenInterface: SourceKitUID = "source.request.editor.open.interface"
        public static let editorOpenHeaderInterface: SourceKitUID = "source.request.editor.open.interface.header"
        public static let editorOpenSwiftSourceInterface: SourceKitUID = "source.request.editor.open.interface.swiftsource"
        public static let editorOpenSwiftTypeInterface: SourceKitUID = "source.request.editor.open.interface.swifttype"
        public static let editorExtractTextFromComment: SourceKitUID = "source.request.editor.extract.comment"
        public static let editorClose: SourceKitUID = "source.request.editor.close"
        public static let editorReplaceText: SourceKitUID = "source.request.editor.replacetext"
        public static let editorFormatText: SourceKitUID = "source.request.editor.formattext"
        public static let editorExpandPlaceholder: SourceKitUID = "source.request.editor.expand_placeholder"
        public static let editorFindUSR: SourceKitUID = "source.request.editor.find_usr"
        public static let editorFindInterfaceDoc: SourceKitUID = "source.request.editor.find_interface_doc"
        public static let buildSettingsRegister: SourceKitUID = "source.request.buildsettings.register"
        public static let moduleGroups: SourceKitUID = "source.request.module.groups"
        public static let nameTranslation: SourceKitUID = "source.request.name.translation"
        public static let markupToXML: SourceKitUID = "source.request.convert.markup.xml"
        public static let statistics: SourceKitUID = "source.request.statistics"
        public static let findRenameRanges: SourceKitUID = "source.request.find-syntactic-rename-ranges"
        public static let findLocalRenameRanges: SourceKitUID = "source.request.find-local-rename-ranges"
        public static let semanticRefactoring: SourceKitUID = "source.request.semantic.refactoring"
        public static let enableCompileNotifications: SourceKitUID = "source.request.enable-compile-notifications"
        public static let testNotification: SourceKitUID = "source.request.test_notification"
        public static let collectExpressionType: SourceKitUID = "source.request.expression.type"
        public static let collectVariableType: SourceKitUID = "source.request.variable.type"
        public static let globalConfiguration: SourceKitUID = "source.request.configuration.global"
        public static let dependencyUpdated: SourceKitUID = "source.request.dependency_updated"
        public static let diagnostics: SourceKitUID = "source.request.diagnostics"
        public static let semanticTokens: SourceKitUID = "source.request.semantic_tokens"
        public static let compile: SourceKitUID = "source.request.compile"
        public static let compileClose: SourceKitUID = "source.request.compile.close"
        public static let enableRequestBarriers: SourceKitUID = "source.request.enable_request_barriers"
        public static let syntacticMacroExpansion: SourceKitUID = "source.request.syntactic_macro_expansion"
        public static let indexToStore: SourceKitUID = "source.request.index_to_store"
        public static let polyglotAST: SourceKitUID = "source.request.polyglot_ast"

        public static let all: [SourceKitUID] = [
            protocolVersion,
            compilerVersion,
            crashWithExit,
            demangle,
            mangleSimpleClass,
            index,
            docInfo,
            codeComplete,
            codeCompleteOpen,
            codeCompleteClose,
            codeCompleteUpdate,
            codeCompleteCacheOnDisk,
            codeCompleteSetPopularAPI,
            codeCompleteSetCustom,
            signatureHelp,
            typeContextInfo,
            conformingMethodList,
            activeRegions,
            cursorInfo,
            rangeInfo,
            relatedIdents,
            editorOpen,
            editorOpenInterface,
            editorOpenHeaderInterface,
            editorOpenSwiftSourceInterface,
            editorOpenSwiftTypeInterface,
            editorExtractTextFromComment,
            editorClose,
            editorReplaceText,
            editorFormatText,
            editorExpandPlaceholder,
            editorFindUSR,
            editorFindInterfaceDoc,
            buildSettingsRegister,
            moduleGroups,
            nameTranslation,
            markupToXML,
            statistics,
            findRenameRanges,
            findLocalRenameRanges,
            semanticRefactoring,
            enableCompileNotifications,
            testNotification,
            collectExpressionType,
            collectVariableType,
            globalConfiguration,
            dependencyUpdated,
            diagnostics,
            semanticTokens,
            compile,
            compileClose,
            enableRequestBarriers,
            syntacticMacroExpansion,
            indexToStore,
            polyglotAST,
        ]
    }

    enum Kind {
        public static let declFunctionFree: SourceKitUID = "source.lang.swift.decl.function.free"
        public static let refFunctionFree: SourceKitUID = "source.lang.swift.ref.function.free"
        public static let declMethodInstance: SourceKitUID = "source.lang.swift.decl.function.method.instance"
        public static let refMethodInstance: SourceKitUID = "source.lang.swift.ref.function.method.instance"
        public static let declMethodStatic: SourceKitUID = "source.lang.swift.decl.function.method.static"
        public static let refMethodStatic: SourceKitUID = "source.lang.swift.ref.function.method.static"
        public static let declMethodClass: SourceKitUID = "source.lang.swift.decl.function.method.class"
        public static let refMethodClass: SourceKitUID = "source.lang.swift.ref.function.method.class"
        public static let declAccessorGetter: SourceKitUID = "source.lang.swift.decl.function.accessor.getter"
        public static let refAccessorGetter: SourceKitUID = "source.lang.swift.ref.function.accessor.getter"
        public static let declAccessorSetter: SourceKitUID = "source.lang.swift.decl.function.accessor.setter"
        public static let refAccessorSetter: SourceKitUID = "source.lang.swift.ref.function.accessor.setter"
        public static let declAccessorWillSet: SourceKitUID = "source.lang.swift.decl.function.accessor.willset"
        public static let refAccessorWillSet: SourceKitUID = "source.lang.swift.ref.function.accessor.willset"
        public static let declAccessorDidSet: SourceKitUID = "source.lang.swift.decl.function.accessor.didset"
        public static let refAccessorDidSet: SourceKitUID = "source.lang.swift.ref.function.accessor.didset"
        public static let declAccessorAddress: SourceKitUID = "source.lang.swift.decl.function.accessor.address"
        public static let refAccessorAddress: SourceKitUID = "source.lang.swift.ref.function.accessor.address"
        public static let declAccessorMutableAddress: SourceKitUID = "source.lang.swift.decl.function.accessor.mutableaddress"
        public static let refAccessorMutableAddress: SourceKitUID = "source.lang.swift.ref.function.accessor.mutableaddress"
        public static let declAccessorRead: SourceKitUID = "source.lang.swift.decl.function.accessor.read"
        public static let refAccessorRead: SourceKitUID = "source.lang.swift.ref.function.accessor.read"
        public static let declAccessorModify: SourceKitUID = "source.lang.swift.decl.function.accessor.modify"
        public static let refAccessorModify: SourceKitUID = "source.lang.swift.ref.function.accessor.modify"
        public static let declAccessorInit: SourceKitUID = "source.lang.swift.decl.function.accessor.init"
        public static let refAccessorInit: SourceKitUID = "source.lang.swift.ref.function.accessor.init"
        public static let declAccessorMutate: SourceKitUID = "source.lang.swift.decl.function.accessor.mutate"
        public static let refAccessorMutate: SourceKitUID = "source.lang.swift.ref.function.accessor.mutate"
        public static let declAccessorBorrow: SourceKitUID = "source.lang.swift.decl.function.accessor.borrow"
        public static let refAccessorBorrow: SourceKitUID = "source.lang.swift.ref.function.accessor.borrow"
        public static let declConstructor: SourceKitUID = "source.lang.swift.decl.function.constructor"
        public static let refConstructor: SourceKitUID = "source.lang.swift.ref.function.constructor"
        public static let declDestructor: SourceKitUID = "source.lang.swift.decl.function.destructor"
        public static let refDestructor: SourceKitUID = "source.lang.swift.ref.function.destructor"
        public static let declFunctionPrefixOperator: SourceKitUID = "source.lang.swift.decl.function.operator.prefix"
        public static let declFunctionPostfixOperator: SourceKitUID = "source.lang.swift.decl.function.operator.postfix"
        public static let declFunctionInfixOperator: SourceKitUID = "source.lang.swift.decl.function.operator.infix"
        public static let refFunctionPrefixOperator: SourceKitUID = "source.lang.swift.ref.function.operator.prefix"
        public static let refFunctionPostfixOperator: SourceKitUID = "source.lang.swift.ref.function.operator.postfix"
        public static let refFunctionInfixOperator: SourceKitUID = "source.lang.swift.ref.function.operator.infix"
        public static let declPrecedenceGroup: SourceKitUID = "source.lang.swift.decl.precedencegroup"
        public static let refPrecedenceGroup: SourceKitUID = "source.lang.swift.ref.precedencegroup"
        public static let declSubscript: SourceKitUID = "source.lang.swift.decl.function.subscript"
        public static let refSubscript: SourceKitUID = "source.lang.swift.ref.function.subscript"
        public static let declVarGlobal: SourceKitUID = "source.lang.swift.decl.var.global"
        public static let refVarGlobal: SourceKitUID = "source.lang.swift.ref.var.global"
        public static let declVarInstance: SourceKitUID = "source.lang.swift.decl.var.instance"
        public static let refVarInstance: SourceKitUID = "source.lang.swift.ref.var.instance"
        public static let declVarStatic: SourceKitUID = "source.lang.swift.decl.var.static"
        public static let refVarStatic: SourceKitUID = "source.lang.swift.ref.var.static"
        public static let declVarClass: SourceKitUID = "source.lang.swift.decl.var.class"
        public static let refVarClass: SourceKitUID = "source.lang.swift.ref.var.class"
        public static let declVarLocal: SourceKitUID = "source.lang.swift.decl.var.local"
        public static let refVarLocal: SourceKitUID = "source.lang.swift.ref.var.local"
        public static let declVarParam: SourceKitUID = "source.lang.swift.decl.var.parameter"
        public static let declModule: SourceKitUID = "source.lang.swift.decl.module"
        public static let declClass: SourceKitUID = "source.lang.swift.decl.class"
        public static let refClass: SourceKitUID = "source.lang.swift.ref.class"
        public static let declActor: SourceKitUID = "source.lang.swift.decl.actor"
        public static let refActor: SourceKitUID = "source.lang.swift.ref.actor"
        public static let declStruct: SourceKitUID = "source.lang.swift.decl.struct"
        public static let refStruct: SourceKitUID = "source.lang.swift.ref.struct"
        public static let declEnum: SourceKitUID = "source.lang.swift.decl.enum"
        public static let refEnum: SourceKitUID = "source.lang.swift.ref.enum"
        public static let declEnumCase: SourceKitUID = "source.lang.swift.decl.enumcase"
        public static let declEnumElement: SourceKitUID = "source.lang.swift.decl.enumelement"
        public static let refEnumElement: SourceKitUID = "source.lang.swift.ref.enumelement"
        public static let declProtocol: SourceKitUID = "source.lang.swift.decl.protocol"
        public static let refProtocol: SourceKitUID = "source.lang.swift.ref.protocol"
        public static let declExtension: SourceKitUID = "source.lang.swift.decl.extension"
        public static let declExtensionStruct: SourceKitUID = "source.lang.swift.decl.extension.struct"
        public static let declExtensionClass: SourceKitUID = "source.lang.swift.decl.extension.class"
        public static let declExtensionEnum: SourceKitUID = "source.lang.swift.decl.extension.enum"
        public static let declExtensionProtocol: SourceKitUID = "source.lang.swift.decl.extension.protocol"
        public static let declAssociatedType: SourceKitUID = "source.lang.swift.decl.associatedtype"
        public static let refAssociatedType: SourceKitUID = "source.lang.swift.ref.associatedtype"
        public static let declOpaqueType: SourceKitUID = "source.lang.swift.decl.opaquetype"
        public static let refOpaqueType: SourceKitUID = "source.lang.swift.ref.opaquetype"
        public static let declTypeAlias: SourceKitUID = "source.lang.swift.decl.typealias"
        public static let refTypeAlias: SourceKitUID = "source.lang.swift.ref.typealias"
        public static let declGenericTypeParam: SourceKitUID = "source.lang.swift.decl.generic_type_param"
        public static let refGenericTypeParam: SourceKitUID = "source.lang.swift.ref.generic_type_param"
        public static let declMacro: SourceKitUID = "source.lang.swift.decl.macro"
        public static let refMacro: SourceKitUID = "source.lang.swift.ref.macro"
        public static let refModule: SourceKitUID = "source.lang.swift.ref.module"
        public static let commentTag: SourceKitUID = "source.lang.swift.commenttag"
        public static let stmtForEach: SourceKitUID = "source.lang.swift.stmt.foreach"
        public static let stmtFor: SourceKitUID = "source.lang.swift.stmt.for"
        public static let stmtWhile: SourceKitUID = "source.lang.swift.stmt.while"
        public static let stmtRepeatWhile: SourceKitUID = "source.lang.swift.stmt.repeatwhile"
        public static let stmtIf: SourceKitUID = "source.lang.swift.stmt.if"
        public static let stmtGuard: SourceKitUID = "source.lang.swift.stmt.guard"
        public static let stmtSwitch: SourceKitUID = "source.lang.swift.stmt.switch"
        public static let stmtCase: SourceKitUID = "source.lang.swift.stmt.case"
        public static let stmtBrace: SourceKitUID = "source.lang.swift.stmt.brace"
        public static let exprCall: SourceKitUID = "source.lang.swift.expr.call"
        public static let exprArg: SourceKitUID = "source.lang.swift.expr.argument"
        public static let exprArray: SourceKitUID = "source.lang.swift.expr.array"
        public static let exprDictionary: SourceKitUID = "source.lang.swift.expr.dictionary"
        public static let exprObjectLiteral: SourceKitUID = "source.lang.swift.expr.object_literal"
        public static let exprTuple: SourceKitUID = "source.lang.swift.expr.tuple"
        public static let exprClosure: SourceKitUID = "source.lang.swift.expr.closure"
        public static let structureElemId: SourceKitUID = "source.lang.swift.structure.elem.id"
        public static let structureElemExpr: SourceKitUID = "source.lang.swift.structure.elem.expr"
        public static let structureElemInitExpr: SourceKitUID = "source.lang.swift.structure.elem.init_expr"
        public static let structureElemCondExpr: SourceKitUID = "source.lang.swift.structure.elem.condition_expr"
        public static let structureElemPattern: SourceKitUID = "source.lang.swift.structure.elem.pattern"
        public static let structureElemTypeRef: SourceKitUID = "source.lang.swift.structure.elem.typeref"
        public static let rangeSingleStatement: SourceKitUID = "source.lang.swift.range.singlestatement"
        public static let rangeSingleExpression: SourceKitUID = "source.lang.swift.range.singleexpression"
        public static let rangeSingleDeclaration: SourceKitUID = "source.lang.swift.range.singledeclaration"
        public static let rangeMultiStatement: SourceKitUID = "source.lang.swift.range.multistatement"
        public static let rangeMultiTypeMemberDeclaration: SourceKitUID = "source.lang.swift.range.multitypememberdeclaration"
        public static let rangeInvalid: SourceKitUID = "source.lang.swift.range.invalid"
        public static let nameObjc: SourceKitUID = "source.lang.name.kind.objc"
        public static let nameSwift: SourceKitUID = "source.lang.name.kind.swift"
        public static let keyword: SourceKitUID = "source.lang.swift.syntaxtype.keyword"
        public static let identifier: SourceKitUID = "source.lang.swift.syntaxtype.identifier"
        public static let `operator`: SourceKitUID = "source.lang.swift.syntaxtype.operator"
        public static let typeIdentifier: SourceKitUID = "source.lang.swift.syntaxtype.typeidentifier"
        public static let buildConfigKeyword: SourceKitUID = "source.lang.swift.syntaxtype.buildconfig.keyword"
        public static let buildConfigId: SourceKitUID = "source.lang.swift.syntaxtype.buildconfig.id"
        public static let poundDirectiveKeyword: SourceKitUID = "source.lang.swift.syntaxtype.pounddirective.keyword"
        public static let attributeId: SourceKitUID = "source.lang.swift.syntaxtype.attribute.id"
        public static let attributeBuiltin: SourceKitUID = "source.lang.swift.syntaxtype.attribute.builtin"
        public static let number: SourceKitUID = "source.lang.swift.syntaxtype.number"
        public static let string: SourceKitUID = "source.lang.swift.syntaxtype.string"
        public static let stringInterpolation: SourceKitUID = "source.lang.swift.syntaxtype.string_interpolation_anchor"
        public static let comment: SourceKitUID = "source.lang.swift.syntaxtype.comment"
        public static let docComment: SourceKitUID = "source.lang.swift.syntaxtype.doccomment"
        public static let docCommentField: SourceKitUID = "source.lang.swift.syntaxtype.doccomment.field"
        public static let commentMarker: SourceKitUID = "source.lang.swift.syntaxtype.comment.mark"
        public static let commentURL: SourceKitUID = "source.lang.swift.syntaxtype.comment.url"
        public static let placeholder: SourceKitUID = "source.lang.swift.syntaxtype.placeholder"
        public static let objectLiteral: SourceKitUID = "source.lang.swift.syntaxtype.objectliteral"
        public static let expr: SourceKitUID = "source.lang.swift.expr"
        public static let stmt: SourceKitUID = "source.lang.swift.stmt"
        public static let type: SourceKitUID = "source.lang.swift.type"
        public static let forEachSequence: SourceKitUID = "source.lang.swift.foreach.sequence"
        public static let diagNote: SourceKitUID = "source.diagnostic.severity.note"
        public static let diagWarning: SourceKitUID = "source.diagnostic.severity.warning"
        public static let diagError: SourceKitUID = "source.diagnostic.severity.error"
        public static let diagRemark: SourceKitUID = "source.diagnostic.severity.remark"
        public static let diagDeprecation: SourceKitUID = "source.diagnostic.category.deprecation"
        public static let diagNoUsage: SourceKitUID = "source.diagnostic.category.no_usage"
        public static let codeCompletionEverything: SourceKitUID = "source.codecompletion.everything"
        public static let codeCompletionModule: SourceKitUID = "source.codecompletion.module"
        public static let codeCompletionKeyword: SourceKitUID = "source.codecompletion.keyword"
        public static let codeCompletionLiteral: SourceKitUID = "source.codecompletion.literal"
        public static let codeCompletionCustom: SourceKitUID = "source.codecompletion.custom"
        public static let codeCompletionIdentifier: SourceKitUID = "source.codecompletion.identifier"
        public static let codeCompletionDescription: SourceKitUID = "source.codecompletion.description"
        public static let editActive: SourceKitUID = "source.edit.kind.active"
        public static let editInactive: SourceKitUID = "source.edit.kind.inactive"
        public static let editSelector: SourceKitUID = "source.edit.kind.selector"
        public static let editString: SourceKitUID = "source.edit.kind.string"
        public static let editComment: SourceKitUID = "source.edit.kind.comment"
        public static let editMismatch: SourceKitUID = "source.edit.kind.mismatch"
        public static let editUnknown: SourceKitUID = "source.edit.kind.unknown"
        public static let renameRangeBase: SourceKitUID = "source.refactoring.range.kind.basename"
        public static let renameRangeKeywordBase: SourceKitUID = "source.refactoring.range.kind.keyword-basename"
        public static let renameRangeParam: SourceKitUID = "source.refactoring.range.kind.parameter-and-whitespace"
        public static let renameRangeNoncollapsibleParam: SourceKitUID = "source.refactoring.range.kind.noncollapsible-parameter"
        public static let renameRangeDeclArgLabel: SourceKitUID = "source.refactoring.range.kind.decl-argument-label"
        public static let renameRangeCallArgLabel: SourceKitUID = "source.refactoring.range.kind.call-argument-label"
        public static let renameRangeCallArgColon: SourceKitUID = "source.refactoring.range.kind.call-argument-colon"
        public static let renameRangeCallArgCombined: SourceKitUID = "source.refactoring.range.kind.call-argument-combined"
        public static let renameRangeSelectorArgLabel: SourceKitUID = "source.refactoring.range.kind.selector-argument-label"
        public static let definition: SourceKitUID = "source.syntacticrename.definition"
        public static let reference: SourceKitUID = "source.syntacticrename.reference"
        public static let call: SourceKitUID = "source.syntacticrename.call"
        public static let unknown: SourceKitUID = "source.syntacticrename.unknown"
        public static let statNumRequests: SourceKitUID = "source.statistic.num-requests"
        public static let statNumSemaRequests: SourceKitUID = "source.statistic.num-semantic-requests"
        public static let statInstructionCount: SourceKitUID = "source.statistic.instruction-count"
        public static let swift: SourceKitUID = "source.lang.swift"
        public static let objC: SourceKitUID = "source.lang.objc"
        public static let macroRoleExpression: SourceKitUID = "source.lang.swift.macro_role.expression"
        public static let macroRoleDeclaration: SourceKitUID = "source.lang.swift.macro_role.declaration"
        public static let macroRoleCodeItem: SourceKitUID = "source.lang.swift.macro_role.codeitem"
        public static let macroRoleAccessor: SourceKitUID = "source.lang.swift.macro_role.accessor"
        public static let macroRoleMemberAttribute: SourceKitUID = "source.lang.swift.macro_role.member_attribute"
        public static let macroRoleMember: SourceKitUID = "source.lang.swift.macro_role.member"
        public static let macroRolePeer: SourceKitUID = "source.lang.swift.macro_role.peer"
        public static let macroRoleConformance: SourceKitUID = "source.lang.swift.macro_role.conformance"
        public static let macroRoleExtension: SourceKitUID = "source.lang.swift.macro_role.extension"
        public static let macroRolePreamble: SourceKitUID = "source.lang.swift.macro_role.preamble"
        public static let macroRoleBody: SourceKitUID = "source.lang.swift.macro_role.body"

        public static let all: [SourceKitUID] = [
            declFunctionFree,
            refFunctionFree,
            declMethodInstance,
            refMethodInstance,
            declMethodStatic,
            refMethodStatic,
            declMethodClass,
            refMethodClass,
            declAccessorGetter,
            refAccessorGetter,
            declAccessorSetter,
            refAccessorSetter,
            declAccessorWillSet,
            refAccessorWillSet,
            declAccessorDidSet,
            refAccessorDidSet,
            declAccessorAddress,
            refAccessorAddress,
            declAccessorMutableAddress,
            refAccessorMutableAddress,
            declAccessorRead,
            refAccessorRead,
            declAccessorModify,
            refAccessorModify,
            declAccessorInit,
            refAccessorInit,
            declAccessorMutate,
            refAccessorMutate,
            declAccessorBorrow,
            refAccessorBorrow,
            declConstructor,
            refConstructor,
            declDestructor,
            refDestructor,
            declFunctionPrefixOperator,
            declFunctionPostfixOperator,
            declFunctionInfixOperator,
            refFunctionPrefixOperator,
            refFunctionPostfixOperator,
            refFunctionInfixOperator,
            declPrecedenceGroup,
            refPrecedenceGroup,
            declSubscript,
            refSubscript,
            declVarGlobal,
            refVarGlobal,
            declVarInstance,
            refVarInstance,
            declVarStatic,
            refVarStatic,
            declVarClass,
            refVarClass,
            declVarLocal,
            refVarLocal,
            declVarParam,
            declModule,
            declClass,
            refClass,
            declActor,
            refActor,
            declStruct,
            refStruct,
            declEnum,
            refEnum,
            declEnumCase,
            declEnumElement,
            refEnumElement,
            declProtocol,
            refProtocol,
            declExtension,
            declExtensionStruct,
            declExtensionClass,
            declExtensionEnum,
            declExtensionProtocol,
            declAssociatedType,
            refAssociatedType,
            declOpaqueType,
            refOpaqueType,
            declTypeAlias,
            refTypeAlias,
            declGenericTypeParam,
            refGenericTypeParam,
            declMacro,
            refMacro,
            refModule,
            commentTag,
            stmtForEach,
            stmtFor,
            stmtWhile,
            stmtRepeatWhile,
            stmtIf,
            stmtGuard,
            stmtSwitch,
            stmtCase,
            stmtBrace,
            exprCall,
            exprArg,
            exprArray,
            exprDictionary,
            exprObjectLiteral,
            exprTuple,
            exprClosure,
            structureElemId,
            structureElemExpr,
            structureElemInitExpr,
            structureElemCondExpr,
            structureElemPattern,
            structureElemTypeRef,
            rangeSingleStatement,
            rangeSingleExpression,
            rangeSingleDeclaration,
            rangeMultiStatement,
            rangeMultiTypeMemberDeclaration,
            rangeInvalid,
            nameObjc,
            nameSwift,
            keyword,
            identifier,
            `operator`,
            typeIdentifier,
            buildConfigKeyword,
            buildConfigId,
            poundDirectiveKeyword,
            attributeId,
            attributeBuiltin,
            number,
            string,
            stringInterpolation,
            comment,
            docComment,
            docCommentField,
            commentMarker,
            commentURL,
            placeholder,
            objectLiteral,
            expr,
            stmt,
            type,
            forEachSequence,
            diagNote,
            diagWarning,
            diagError,
            diagRemark,
            diagDeprecation,
            diagNoUsage,
            codeCompletionEverything,
            codeCompletionModule,
            codeCompletionKeyword,
            codeCompletionLiteral,
            codeCompletionCustom,
            codeCompletionIdentifier,
            codeCompletionDescription,
            editActive,
            editInactive,
            editSelector,
            editString,
            editComment,
            editMismatch,
            editUnknown,
            renameRangeBase,
            renameRangeKeywordBase,
            renameRangeParam,
            renameRangeNoncollapsibleParam,
            renameRangeDeclArgLabel,
            renameRangeCallArgLabel,
            renameRangeCallArgColon,
            renameRangeCallArgCombined,
            renameRangeSelectorArgLabel,
            definition,
            reference,
            call,
            unknown,
            statNumRequests,
            statNumSemaRequests,
            statInstructionCount,
            swift,
            objC,
            macroRoleExpression,
            macroRoleDeclaration,
            macroRoleCodeItem,
            macroRoleAccessor,
            macroRoleMemberAttribute,
            macroRoleMember,
            macroRolePeer,
            macroRoleConformance,
            macroRoleExtension,
            macroRolePreamble,
            macroRoleBody,
        ]
    }
}
