#include "CSourceKitDShim.h"

// Generated by Tools/generate-sourcekitd-shim.swift. Do not edit by hand.

typedef struct {
    SwiftSourceKitDVariantDictionaryApplier applier;
    void *context;
} SwiftSourceKitDVariantDictionaryContext;

static bool swift_sourcekitd_variant_dictionary_apply_bridge(
    void *key,
    SwiftSourceKitDVariant value,
    void *context
) {
    SwiftSourceKitDVariantDictionaryContext *bridgeContext = context;
    return bridgeContext->applier(key, &value, bridgeContext->context);
}

void swift_sourcekitd_response_get_value(
    void *function,
    void * resp,
    SwiftSourceKitDVariant *out
) {
    typedef SwiftSourceKitDVariant (*Function)(void *);
    *out = ((Function)function)(resp);
}

size_t swift_sourcekitd_variant_array_get_count(
    void *function,
    SwiftSourceKitDVariant * array
) {
    typedef size_t (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*array);
}

void swift_sourcekitd_variant_array_get_value(
    void *function,
    SwiftSourceKitDVariant * array,
    size_t index,
    SwiftSourceKitDVariant *out
) {
    typedef SwiftSourceKitDVariant (*Function)(SwiftSourceKitDVariant, size_t);
    *out = ((Function)function)(*array, index);
}

bool swift_sourcekitd_variant_bool_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef bool (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

const void * swift_sourcekitd_variant_data_get_ptr(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef const void * (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

size_t swift_sourcekitd_variant_data_get_size(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef size_t (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

bool swift_sourcekitd_variant_dictionary_apply(
    void *function,
    SwiftSourceKitDVariant *dictionary,
    SwiftSourceKitDVariantDictionaryApplier applier,
    void *context
) {
    typedef bool (*Function)(SwiftSourceKitDVariant, bool (*)(void *, SwiftSourceKitDVariant, void *), void *);
    SwiftSourceKitDVariantDictionaryContext bridgeContext = { applier, context };
    return ((Function)function)(*dictionary, swift_sourcekitd_variant_dictionary_apply_bridge, &bridgeContext);
}

int64_t swift_sourcekitd_variant_dictionary_get_int64(
    void *function,
    SwiftSourceKitDVariant * dict,
    void * key
) {
    typedef int64_t (*Function)(SwiftSourceKitDVariant, void *);
    return ((Function)function)(*dict, key);
}

const char * swift_sourcekitd_variant_dictionary_get_string(
    void *function,
    SwiftSourceKitDVariant * dict,
    void * key
) {
    typedef const char * (*Function)(SwiftSourceKitDVariant, void *);
    return ((Function)function)(*dict, key);
}

void * swift_sourcekitd_variant_dictionary_get_uid(
    void *function,
    SwiftSourceKitDVariant * dict,
    void * key
) {
    typedef void * (*Function)(SwiftSourceKitDVariant, void *);
    return ((Function)function)(*dict, key);
}

void swift_sourcekitd_variant_dictionary_get_value(
    void *function,
    SwiftSourceKitDVariant * dict,
    void * key,
    SwiftSourceKitDVariant *out
) {
    typedef SwiftSourceKitDVariant (*Function)(SwiftSourceKitDVariant, void *);
    *out = ((Function)function)(*dict, key);
}

double swift_sourcekitd_variant_double_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef double (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

int32_t swift_sourcekitd_variant_get_type(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef int32_t (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

int64_t swift_sourcekitd_variant_int64_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef int64_t (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

const char * swift_sourcekitd_variant_string_get_ptr(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef const char * (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}

void * swift_sourcekitd_variant_uid_get_value(
    void *function,
    SwiftSourceKitDVariant * obj
) {
    typedef void * (*Function)(SwiftSourceKitDVariant);
    return ((Function)function)(*obj);
}
