#!/usr/bin/env swift

import Foundation

struct Function {
    let returnType: String
    let name: String
    let parameters: [Parameter]
}

struct Parameter {
    let type: String
    let name: String
}

struct CTypeMapping {
    let shim: String
    let functionPointerReturn: String
    let functionPointerParameter: String
    let isVariant: Bool
}

let generatedNotice = "Generated by Tools/generate-sourcekitd-shim.swift. Do not edit by hand."
let shimmedFunctions = Set([
    "sourcekitd_response_get_value",
    "sourcekitd_variant_get_type",
    "sourcekitd_variant_int64_get_value",
    "sourcekitd_variant_bool_get_value",
    "sourcekitd_variant_double_get_value",
    "sourcekitd_variant_string_get_ptr",
    "sourcekitd_variant_data_get_size",
    "sourcekitd_variant_data_get_ptr",
    "sourcekitd_variant_uid_get_value",
    "sourcekitd_variant_dictionary_apply_f",
    "sourcekitd_variant_array_get_count",
    "sourcekitd_variant_array_get_value",
])
let cTypeMappings: [String: CTypeMapping] = [
    "sourcekitd_variant_t": CTypeMapping(
        shim: "SwiftSourceKitDVariant *",
        functionPointerReturn: "SwiftSourceKitDVariant",
        functionPointerParameter: "SwiftSourceKitDVariant",
        isVariant: true
    ),
    "sourcekitd_variant_type_t": CTypeMapping(
        shim: "int32_t",
        functionPointerReturn: "int32_t",
        functionPointerParameter: "int32_t",
        isVariant: false
    ),
    "const char *": CTypeMapping(
        shim: "const char *",
        functionPointerReturn: "const char *",
        functionPointerParameter: "const char *",
        isVariant: false
    ),
    "int64_t": CTypeMapping(
        shim: "int64_t",
        functionPointerReturn: "int64_t",
        functionPointerParameter: "int64_t",
        isVariant: false
    ),
    "bool": CTypeMapping(
        shim: "bool",
        functionPointerReturn: "bool",
        functionPointerParameter: "bool",
        isVariant: false
    ),
    "double": CTypeMapping(
        shim: "double",
        functionPointerReturn: "double",
        functionPointerParameter: "double",
        isVariant: false
    ),
    "const void *": CTypeMapping(
        shim: "const void *",
        functionPointerReturn: "const void *",
        functionPointerParameter: "const void *",
        isVariant: false
    ),
    "size_t": CTypeMapping(
        shim: "size_t",
        functionPointerReturn: "size_t",
        functionPointerParameter: "size_t",
        isVariant: false
    ),
    "void *": CTypeMapping(
        shim: "void *",
        functionPointerReturn: "void *",
        functionPointerParameter: "void *",
        isVariant: false
    ),
    "sourcekitd_response_t": CTypeMapping(
        shim: "void *",
        functionPointerReturn: "void *",
        functionPointerParameter: "void *",
        isVariant: false
    ),
    "sourcekitd_uid_t": CTypeMapping(
        shim: "void *",
        functionPointerReturn: "void *",
        functionPointerParameter: "void *",
        isVariant: false
    ),
]

func parseFunctions(from header: String) -> [Function] {
    let collapsed = header
        .replacingOccurrences(of: #"/\*.*?\*/"#, with: "", options: .regularExpression)
        .replacingOccurrences(of: #"SOURCEKITD_[A-Z0-9_]+"#, with: "", options: .regularExpression)
        .replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)

    let pattern = #"([A-Za-z_][A-Za-z0-9_\s]*(?:\s*\*)*)\s*(sourcekitd_[A-Za-z0-9_]+)\s*\(([^;{}]*)\)\s*;"#
    let regex = try! NSRegularExpression(pattern: pattern)
    let range = NSRange(collapsed.startIndex..<collapsed.endIndex, in: collapsed)

    return regex.matches(in: collapsed, range: range).compactMap { match in
        guard
            let returnRange = Range(match.range(at: 1), in: collapsed),
            let nameRange = Range(match.range(at: 2), in: collapsed),
            let parameterRange = Range(match.range(at: 3), in: collapsed)
        else {
            return nil
        }

        let name = String(collapsed[nameRange])
        guard shimmedFunctions.contains(name) else {
            return nil
        }

        let returnType = normalizeType(String(collapsed[returnRange]))
        let parameters = parseParameters(String(collapsed[parameterRange]))
        return Function(returnType: returnType, name: name, parameters: parameters)
    }
}

func parseParameters(_ text: String) -> [Parameter] {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty, trimmed != "void" else {
        return []
    }

    return trimmed.split(separator: ",").enumerated().map { index, raw in
        let parameter = raw
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: #"\s*\*\s*([A-Za-z_])"#, with: " * $1", options: .regularExpression)
        let pieces = parameter.split(separator: " ")
        guard let name = pieces.last else {
            return Parameter(type: normalizeType(parameter), name: "parameter\(index)")
        }

        let type = parameter.dropLast(name.count).trimmingCharacters(in: .whitespacesAndNewlines)
        return Parameter(type: normalizeType(type), name: String(name))
    }
}

func normalizeType(_ text: String) -> String {
    text
        .replacingOccurrences(of: #" ?\* ?"#, with: " *", options: .regularExpression)
        .replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

func renderHeader(functions: [Function]) -> String {
    var lines: [String] = []
    lines.append("#ifndef C_SOURCE_KIT_D_SHIM_H")
    lines.append("#define C_SOURCE_KIT_D_SHIM_H")
    lines.append("")
    lines.append("// \(generatedNotice)")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint64_t data[3];")
    lines.append("} SwiftSourceKitDVariant;")
    lines.append("")
    lines.append("typedef bool (*SwiftSourceKitDVariantDictionaryApplier)(")
    lines.append("    void *key,")
    lines.append("    SwiftSourceKitDVariant *value,")
    lines.append("    void *context")
    lines.append(");")
    lines.append("")
    for function in functions {
        lines.append(renderHeaderDeclaration(function))
    }
    lines.append("#endif")
    lines.append("")
    return lines.joined(separator: "\n")
}

func renderSource(functions: [Function]) -> String {
    var lines: [String] = []
    lines.append(#"#include "CSourceKitDShim.h""#)
    lines.append("")
    lines.append("// \(generatedNotice)")
    lines.append("")
    if functions.contains(where: { $0.name == "sourcekitd_variant_dictionary_apply_f" }) {
        lines.append(renderDictionaryApplyBridgeSupport())
    }
    for function in functions {
        lines.append(renderImplementation(function))
    }
    return lines.joined(separator: "\n")
}

func renderHeaderDeclaration(_ function: Function) -> String {
    let shimName = shimName(for: function.name)
    if function.name == "sourcekitd_variant_dictionary_apply_f" {
        return """
        bool \(shimName)(
            void *function,
            SwiftSourceKitDVariant *dictionary,
            SwiftSourceKitDVariantDictionaryApplier applier,
            void *context
        );
        """
    }

    if isVariant(function.returnType) {
        let parameters = ["void *function"] + function.parameters.map(renderShimParameter) + ["SwiftSourceKitDVariant *out"]
        return "void \(shimName)(\n    \(parameters.joined(separator: ",\n    "))\n);"
    }

    let parameters = ["void *function"] + function.parameters.map(renderShimParameter)
    return "\(shimReturnType(function.returnType)) \(shimName)(\n    \(parameters.joined(separator: ",\n    "))\n);"
}

func renderImplementation(_ function: Function) -> String {
    let shimName = shimName(for: function.name)
    if function.name == "sourcekitd_variant_dictionary_apply_f" {
        return """
        bool \(shimName)(
            void *function,
            SwiftSourceKitDVariant *dictionary,
            SwiftSourceKitDVariantDictionaryApplier applier,
            void *context
        ) {
            typedef bool (*Function)(SwiftSourceKitDVariant, bool (*)(void *, SwiftSourceKitDVariant, void *), void *);
            SwiftSourceKitDVariantDictionaryContext bridgeContext = { applier, context };
            return ((Function)function)(*dictionary, swift_sourcekitd_variant_dictionary_apply_bridge, &bridgeContext);
        }

        """
    }

    let functionType = "typedef \(functionPointerReturnType(function.returnType)) (*Function)(\(function.parameters.map(functionPointerParameterType).joined(separator: ", ")));"
    let callArguments = function.parameters.map(callArgument).joined(separator: ", ")

    var lines: [String] = []
    if isVariant(function.returnType) {
        let parameters = ["void *function"] + function.parameters.map(renderShimParameter) + ["SwiftSourceKitDVariant *out"]
        lines.append("void \(shimName)(\n    \(parameters.joined(separator: ",\n    "))\n) {")
        lines.append("    \(functionType)")
        lines.append("    *out = ((Function)function)(\(callArguments));")
        lines.append("}")
    } else {
        let parameters = ["void *function"] + function.parameters.map(renderShimParameter)
        lines.append("\(shimReturnType(function.returnType)) \(shimName)(\n    \(parameters.joined(separator: ",\n    "))\n) {")
        lines.append("    \(functionType)")
        lines.append("    return ((Function)function)(\(callArguments));")
        lines.append("}")
    }

    lines.append("")
    return lines.joined(separator: "\n")
}

func renderShimParameter(_ parameter: Parameter) -> String {
    "\(shimParameterType(parameter.type)) \(parameter.name)"
}

func shimName(for sourceKitName: String) -> String {
    sourceKitName
        .replacingOccurrences(of: "sourcekitd_", with: "swift_sourcekitd_")
        .replacingOccurrences(of: "_apply_f", with: "_apply")
}

func shimReturnType(_ type: String) -> String {
    mapping(for: type, "return type").shim
}

func shimParameterType(_ type: String) -> String {
    mapping(for: type, "parameter type").shim
}

func functionPointerReturnType(_ type: String) -> String {
    mapping(for: type, "function pointer return type").functionPointerReturn
}

func functionPointerParameterType(_ parameter: Parameter) -> String {
    mapping(for: parameter.type, "function pointer parameter type").functionPointerParameter
}

func callArgument(_ parameter: Parameter) -> String {
    isVariant(parameter.type) ? "*\(parameter.name)" : parameter.name
}

func isVariant(_ type: String) -> Bool {
    cTypeMappings[type]?.isVariant == true
}

func mapping(for type: String, _ context: String) -> CTypeMapping {
    guard let mapping = cTypeMappings[type] else {
        fatalError("unsupported \(context): \(type)")
    }
    return mapping
}

func renderDictionaryApplyBridgeSupport() -> String {
    """
    typedef struct {
        SwiftSourceKitDVariantDictionaryApplier applier;
        void *context;
    } SwiftSourceKitDVariantDictionaryContext;

    static bool swift_sourcekitd_variant_dictionary_apply_bridge(
        void *key,
        SwiftSourceKitDVariant value,
        void *context
    ) {
        SwiftSourceKitDVariantDictionaryContext *bridgeContext = context;
        return bridgeContext->applier(key, &value, bridgeContext->context);
    }

    """
}

func write(_ text: String, to path: String) throws {
    try text.write(toFile: path, atomically: true, encoding: .utf8)
}

func generatedFiles(from headerPath: String) throws -> [(relativePath: String, contents: String)] {
    let header = try String(contentsOfFile: headerPath, encoding: .utf8)
    let functions = parseFunctions(from: header).sorted { $0.name < $1.name }
    guard functions.count == shimmedFunctions.count else {
        let parsed = Set(functions.map(\.name))
        let missing = shimmedFunctions.subtracting(parsed).sorted().joined(separator: ", ")
        fatalError("sourcekitd.h did not contain expected shim functions: \(missing)")
    }

    return [
        ("include/CSourceKitDShim.h", renderHeader(functions: functions)),
        ("CSourceKitDShim.c", renderSource(functions: functions)),
    ]
}

func writeGeneratedFiles(headerPath: String, outputDirectory: String) throws {
    try FileManager.default.createDirectory(atPath: "\(outputDirectory)/include", withIntermediateDirectories: true)
    for file in try generatedFiles(from: headerPath) {
        try write(file.contents, to: "\(outputDirectory)/\(file.relativePath)")
    }
}

func verifyGeneratedFiles(headerPath: String, outputDirectory: String) throws {
    var failures: [String] = []
    for file in try generatedFiles(from: headerPath) {
        let path = "\(outputDirectory)/\(file.relativePath)"
        let current = try String(contentsOfFile: path, encoding: .utf8)
        if current != file.contents {
            failures.append(file.relativePath)
        }
    }

    guard failures.isEmpty else {
        fatalError("generated shim is out of date: \(failures.joined(separator: ", "))")
    }
    print("SourceKitD shim verification passed")
}

func runSelfTest() {
    let fixture = """
    typedef struct { uint64_t data[3]; } sourcekitd_variant_t;
    typedef void *sourcekitd_response_t;
    typedef void *sourcekitd_uid_t;
    typedef int32_t sourcekitd_variant_type_t;
    typedef bool (*sourcekitd_variant_dictionary_applier_f_t)(sourcekitd_uid_t key, sourcekitd_variant_t value, void *context);

    sourcekitd_variant_t sourcekitd_response_get_value(sourcekitd_response_t response);
    sourcekitd_variant_type_t sourcekitd_variant_get_type(sourcekitd_variant_t variant);
    int64_t sourcekitd_variant_int64_get_value(sourcekitd_variant_t variant);
    bool sourcekitd_variant_bool_get_value(sourcekitd_variant_t variant);
    double sourcekitd_variant_double_get_value(sourcekitd_variant_t variant);
    const char *sourcekitd_variant_string_get_ptr(sourcekitd_variant_t variant);
    size_t sourcekitd_variant_data_get_size(sourcekitd_variant_t variant);
    const void *sourcekitd_variant_data_get_ptr(sourcekitd_variant_t variant);
    sourcekitd_uid_t sourcekitd_variant_uid_get_value(sourcekitd_variant_t variant);
    bool sourcekitd_variant_dictionary_apply_f(sourcekitd_variant_t dict, sourcekitd_variant_dictionary_applier_f_t applier, void *context);
    size_t sourcekitd_variant_array_get_count(sourcekitd_variant_t array);
    sourcekitd_variant_t sourcekitd_variant_array_get_value(sourcekitd_variant_t array, size_t index);
    """

    let functions = parseFunctions(from: fixture)
    precondition(Set(functions.map(\.name)) == shimmedFunctions, "parsed shim function set changed")
    precondition(renderHeader(functions: functions).contains("SwiftSourceKitDVariant *out"), "variant return should use out pointer")
    precondition(renderSource(functions: functions).contains("*out = ((Function)function)(response);"), "variant call should assign out value")
    print("SourceKitD shim generator self-test passed")
}

let arguments = Array(CommandLine.arguments.dropFirst())

if arguments == ["--self-test"] {
    runSelfTest()
} else if arguments.count == 4, arguments[0] == "--sourcekitd-header", arguments[2] == "--output" {
    try writeGeneratedFiles(headerPath: arguments[1], outputDirectory: arguments[3])
} else if arguments.count == 5, arguments[0] == "--verify", arguments[1] == "--sourcekitd-header", arguments[3] == "--output" {
    try verifyGeneratedFiles(headerPath: arguments[2], outputDirectory: arguments[4])
} else {
    fputs("usage: generate-sourcekitd-shim.swift --sourcekitd-header <path> --output Sources/CSourceKitDShim\n", stderr)
    fputs("       generate-sourcekitd-shim.swift --verify --sourcekitd-header <path> --output Sources/CSourceKitDShim\n", stderr)
    fputs("       generate-sourcekitd-shim.swift --self-test\n", stderr)
    exit(2)
}
