#!/usr/bin/env swift

import Foundation

struct UIDEntry {
    let kind: String
    let internalName: String
    let externalName: String

    var swiftName: String {
        swiftIdentifier(for: internalName)
    }
}

let generatedNotice = "Generated by Tools/generate-sourcekit-uid-constants.swift. Do not edit by hand."
let defaultInput = "Tests/Fixtures/sourcekit/UIDs.py"
let defaultOutput = "Sources/SwiftSourceKit/SourceKitKeys.swift"

let keywordNames = Set([
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "continue", "default", "defer",
    "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat",
    "return", "switch", "where", "while", "as", "catch", "false", "is",
    "nil", "rethrows", "super", "self", "throw", "throws", "true", "try",
])

let exactNameOverrides = [
    "USR": "usr",
    "USRs": "usrs",
    "UIDs": "uids",
    "ID": "id",
    "VFS": "vfs",
    "ObjC": "objC",
    "AssociatedUSRs": "associatedUSRs",
]

func swiftIdentifier(for name: String) -> String {
    if let override = exactNameOverrides[name] {
        return override
    }

    let pattern = #"[A-Z]+(?=[A-Z][a-z]|$)|[A-Z]?[a-z]+|[0-9]+"#
    let regex = try! NSRegularExpression(pattern: pattern)
    let range = NSRange(name.startIndex..<name.endIndex, in: name)
    let pieces = regex.matches(in: name, range: range).compactMap { match -> String? in
        guard let range = Range(match.range, in: name) else { return nil }
        return String(name[range])
    }

    guard let first = pieces.first else {
        return name
    }

    let rest = pieces.dropFirst().map { piece in
        if piece.allSatisfy(\.isUppercase) || piece.allSatisfy(\.isNumber) {
            return piece
        }
        return piece.prefix(1).uppercased() + piece.dropFirst()
    }

    return ([first.lowercased()] + rest).joined()
}

func declarationName(_ name: String) -> String {
    keywordNames.contains(name) ? "`\(name)`" : name
}

func parseEntries(from input: String) -> [UIDEntry] {
    let pattern = #"(KEY|REQUEST|KIND)\(\s*'([^']+)'\s*,\s*'([^']+)'\s*\)"#
    let regex = try! NSRegularExpression(pattern: pattern, options: [.dotMatchesLineSeparators])
    let range = NSRange(input.startIndex..<input.endIndex, in: input)

    return regex.matches(in: input, range: range).compactMap { match in
        guard
            let kindRange = Range(match.range(at: 1), in: input),
            let internalRange = Range(match.range(at: 2), in: input),
            let externalRange = Range(match.range(at: 3), in: input)
        else {
            return nil
        }

        return UIDEntry(
            kind: String(input[kindRange]),
            internalName: String(input[internalRange]),
            externalName: String(input[externalRange])
        )
    }
}

func render(entries: [UIDEntry]) -> String {
    let keys = entries.filter { $0.kind == "KEY" }
    let requests = entries.filter { $0.kind == "REQUEST" }
    let kinds = entries.filter { $0.kind == "KIND" }

    let rootAliasEntries = unambiguousRootAliases(keys: keys, requests: requests)
    let compatibilityAliases: [(String, String)] = [
        ("compilerArguments", "Key.compilerArgs"),
        ("declarationFile", "Key.filePath"),
        ("declarationOffset", "Key.offset"),
    ]

    var lines: [String] = []
    lines.append("// \(generatedNotice)")
    lines.append("// Source of truth: Tests/Fixtures/sourcekit/UIDs.py.")
    lines.append("")
    lines.append("public extension SourceKitUID {")
    lines.append("    // Root aliases cover keys and requests with unambiguous Swift names.")
    for entry in rootAliasEntries {
        lines.append("    static let \(declarationName(entry.swiftName)) = \(entry.kind == "KEY" ? "Key" : "Request").\(declarationName(entry.swiftName))")
    }
    for alias in compatibilityAliases where !rootAliasEntries.contains(where: { $0.swiftName == alias.0 }) {
        lines.append("    static let \(declarationName(alias.0)) = \(alias.1)")
    }
    lines.append("")
    lines.append(renderNamespace(name: "Key", entries: keys))
    lines.append("")
    lines.append(renderNamespace(name: "Request", entries: requests))
    lines.append("")
    lines.append(renderNamespace(name: "Kind", entries: kinds))
    lines.append("}")
    lines.append("")
    return lines.joined(separator: "\n")
}

func unambiguousRootAliases(keys: [UIDEntry], requests: [UIDEntry]) -> [UIDEntry] {
    let entries = keys + requests
    let counts = Dictionary(grouping: entries, by: \.swiftName).mapValues(\.count)
    return entries.filter { counts[$0.swiftName] == 1 }
}

func renderNamespace(name: String, entries: [UIDEntry]) -> String {
    var lines: [String] = []
    lines.append("    enum \(name) {")
    for entry in entries {
        lines.append("        public static let \(declarationName(entry.swiftName)): SourceKitUID = \(String(reflecting: entry.externalName))")
    }
    lines.append("")
    lines.append("        public static let all: [SourceKitUID] = [")
    for entry in entries {
        lines.append("            \(declarationName(entry.swiftName)),")
    }
    lines.append("        ]")
    lines.append("    }")
    return lines.joined(separator: "\n")
}

func fileContents(at path: String) throws -> String {
    try String(contentsOfFile: path, encoding: .utf8)
}

func write(_ output: String, to path: String) throws {
    try output.write(toFile: path, atomically: true, encoding: .utf8)
}

func runSelfTest() {
    let sample = """
    UID_KEYS = [
        KEY('CompilerArgs', 'key.compilerargs'),
        KEY('SemanticTokens', 'key.semantic_tokens'),
    ]
    UID_REQUESTS = [
        REQUEST('SemanticTokens', 'source.request.semantic_tokens'),
    ]
    UID_KINDS = [
        KIND('ObjC', 'source.lang.objc'),
        KIND('Operator', 'source.lang.swift.syntaxtype.operator'),
    ]
    """

    let rendered = render(entries: parseEntries(from: sample))
    precondition(rendered.contains("static let compilerArgs"))
    precondition(!rendered.contains("static let semanticTokens ="))
    precondition(rendered.contains("public static let objC"))
    precondition(rendered.contains("public static let `operator`"))
}

var inputPath = defaultInput
var outputPath = defaultOutput
var verify = false
var selfTest = false

var arguments = Array(CommandLine.arguments.dropFirst())
while let argument = arguments.first {
    arguments.removeFirst()
    switch argument {
    case "--input":
        inputPath = arguments.removeFirst()
    case "--output":
        outputPath = arguments.removeFirst()
    case "--verify":
        verify = true
    case "--self-test":
        selfTest = true
    default:
        fatalError("Unknown argument: \(argument)")
    }
}

if selfTest {
    runSelfTest()
}

let input = try fileContents(at: inputPath)
let output = render(entries: parseEntries(from: input))

if verify {
    let existing = try fileContents(at: outputPath)
    if existing != output {
        fputs("\(outputPath) is out of date. Run Tools/generate-sourcekit-uid-constants.swift.\n", stderr)
        exit(1)
    }
} else {
    try write(output, to: outputPath)
}
